name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.17.0', '20.x', '22.x']
        n8n-workflow-version: ['1.95.0', '1.95.1', '1.95.2', '1.95.3']
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Install n8n-workflow version ${{ matrix.n8n-workflow-version }}
        run: npm install n8n-workflow@${{ matrix.n8n-workflow-version }}
      - name: Lint
        run: npm run lint
      - name: n8n Community Package Scan
        run: npm run scan
      - name: Build
        run: npm run build
      - name: Run tests with coverage
        run: npm run test
