name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.17.0', '20.14.0', '22.16.0']
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Install latest n8n and n8n-workflow
        run: npm install n8n@latest n8n-workflow@latest
      - name: Lint
        run: npm run lint
      - name: n8n Community Package Scan
        run: npm run scan
      - name: Build
        run: npm run build
      - name: Run tests with coverage
        run: npm run test
