name: Publish

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up git user for CI
        run: |
          git config user.name "FactoryIQ CI"
          git config user.email "noreply@factoryiq.ch"
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Use Node.js 18.17.0
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
          registry-url: 'https://registry.npmjs.org/'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Release (standard-version)
        run: npm run release
      - name: Push changes and tags
        run: git push --follow-tags origin main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Create GitHub Release
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          gh release create "$LATEST_TAG" --notes-file CHANGELOG.md --title "$LATEST_TAG" --latest
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
