name: Publish

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Set up git user for CI
        run: |
          git config user.name "FactoryIQ CI"
          git config user.email "noreply@factoryiq.ch"
      - name: Use Node.js 18.17.0
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
          registry-url: 'https://registry.npmjs.org/'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Release (standard-version)
        run: npm run release
      - name: Push tags only
        run: |
          # Only push the tags, skip pushing to main branch
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub Release
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          gh release create "$LATEST_TAG" --notes-file CHANGELOG.md --title "$LATEST_TAG" --latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
